### PR TITLE
Added as_json method for rails JSON responses

### PR DESCRIPTION
**Pull request by stakach**
Added as_json method for rails JSON responses

Allows the following to occur in a controller:
`render :json => model.as_json(:except => :some_secret_field)`

Where `model` is a `Couchbase::Model`

I've also written a deterministic id generator based on the counter id pattern at http://couchbasemodels.com/ if you are interested in including it?
Supports up to 340282366920938463426481119284349108225 documents of each model per cluster before manual intervention is required. Has built in XDCR support to avoid any id clashes too.

### CODE REVIEW

**Comment by avsej** [comment]
Hi, Stephen 

Thanks for patch, it seems like I don't receive notification here. (next time just mention @avsej here :)

This repository is just mirror of our primary one, which integrated with gerrit code review tool. Could you please register (it is simple with openid) and accept our CLA. After that I can merge your patch which I've uploaded there already http://review.couchbase.org/23391

Next time it would be faster if you will make gerrit patch and put me in reviewers list.

Thank you again.

## 

Sergey Avseyev

**Comment by avsej** [comment]
And of course I always interested in contributions. Just ping me if you have some code

**Comment by stakach** [comment]
Thanks @avsej I've registered and accepted the CLA.

**Comment by avsej** [comment]
merged, thanks

**Pull request closed without merging**
