### PR TITLE
Added Mass Assignment Security

### LINKED ISSUE #10: Add MassAssignmentSecurity
Working on this now... should have a pull request by this weekend.

I wanted to get feedback if the following structure was ok for adding Mass Assignment support.

I figured unlike ActiveRecord we need to explicitly state what attributes exist in the model for Couchbase-Model. 

If we then wanted to define what attributes are accessible or protected we would follow the expected convention from ActiveModel::MassAssignmentSecurity.

``` ruby
require 'couchbase/model'

class Post < Couchbase::Model
  attribute :title
  attribute :body
  attribute :draft

  attr_accessible :title, :as => admin
  attr_accessible :body, :as => user

end
```

And to Save if you needed to provide a role you could as part of the options hash

``` ruby
    p = Post.new(
                 :body  => 'filter',
                 :title => 'Hello world',
                 :draft => true)
    p.save(:as=> :admin)
```

### PR DESCRIPTION
**Pull request by jabberfest**
[Fixes #10] - Added ActiveModel::MassAssignmentSecurity support.

### CODE REVIEW

**Comment by jabberfest** [comment]
Pull Request isn't ready to be merged. I need to update the tests.... Not sure how you have it setup but when I run rake test I get tests failing with "NoMethodError: undefined method `sanitize_for_mass_assignment' for #Post:0x0000000205c7b8"

Can you help look into it? Looks like ActiveModel::MassAssignmentSecurity doesn't get loaded in the test environment.

``` 'ruby
    if defined?(::Rails)
      extend ActiveModel::Callbacks
      extend ActiveModel::Naming
      include ActiveModel::Conversion
      include ActiveModel::Validations
      include ActiveModel::MassAssignmentSecurity
```

My changes work fine if I test manually from a rails app using the same models used in the unit tests.

**Comment by avsej** [comment]
Looks good to me, I will merge it when some smoke tests will be available

**Comment by avsej** [comment]
Probably this patch will help http://review.couchbase.org/26137

**Comment by jabberfest** [comment]
Thanks I will try that. I have it working now. Need to finish tests before I add commits to this pull request. Will have it in a day or so.

**Comment by jabberfest** [comment]
Should be good to go :-) Let me know if you disagree with anything.

**Comment by avsej** [comment]
Moved to review system http://review.couchbase.org/26236

**Comment by avsej** [comment]
Fixed in 99fa4825fc74dfc2cf522b75d797b02512001d58, @ingenthr could you close the ticket?

**Comment by farias-r7** [comment]
I'm confused. The commit you referenced refers to "Support for batch finding multiple objects by id".

**Comment by ka8725** [comment]
@farias-r7 , your pull request on code review - http://review.couchbase.org/#/c/26236/2

**Comment by jabberfest** [comment]
Not sure if this review is a low priority. I know you guys are busy. I'm just using my own branch hoping this gets merged in, but I'm gonna be in a crappy state if it doesn't. 

I don't want to maintain my own fork for a simple fix :-)

**Comment by ka8725** [comment]
Rails 4 doesn't has mass assignment security out of the box. Developers moved it to the gem. Also today there is a trend to use strong parameters gem. So I think you have to choices - move your changes to the separated gem or use strong parameters aapproach. @avsej what do you think?

**Comment by jabberfest** [comment]
Closing ticket. @ka8725 you are right. I just looked into Rails 4 and it makes sense to go the strong parameters route. Thanks for the info!

Please close the associated ticket in your internal ticket system.

**Pull request closed without merging**
